source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/general/plugins.vim
source $HOME/.config/nvim/plugins/onedark.vim
source $HOME/.config/nvim/plugins/telescope.vim
source $HOME/.config/nvim/plugins/nerdtree.vim
source $HOME/.config/nvim/general/bindings.vim
source $HOME/.config/nvim/plugins/rainbows.vim
source $HOME/.config/nvim/plugins/airlines.vim
source $HOME/.config/nvim/general/functions.vim
